### PR TITLE
style: make utility classes proper utilities

### LINKED ISSUE #340: Hide constructors of utility classes
## Bug report for Cloudinary Java SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
These classes:
- [`ApiUtils`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-http5/src/main/java/com/cloudinary/http5/ApiUtils.java),
- [`SmartUrlEncoder`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/SmartUrlEncoder.java),
- [`Util`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/Util.java),
- [`HtmlEscape`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/utils/HtmlEscape.java),
- [`StringUtils`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/utils/StringUtils.java),
- [`ObjectUtils`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/utils/ObjectUtils.java),
- [`Base64Map`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-core/src/main/java/com/cloudinary/utils/Base64Map.java),
- [`Feature`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-test-common/src/main/java/com/cloudinary/test/helpers/Feature.java),
- [`MetadataTestHelper`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-test-common/src/main/java/com/cloudinary/test/MetadataTestHelper.java),
- [`Singleton`](https://github.com/cloudinary/cloudinary_java/blob/43d8e9ac0c7f073017d9c4b566c9566dea95f205/cloudinary-taglib/src/main/java/com/cloudinary/Singleton.java),

are _utilities_ and their constructors should be hidden and they should be marked as `final`. Such change makes it harder to misuse them (prevents instantiation and inheritance) and makes the coverage reports more accurate.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[x] Other (Specify) - code quality

Related to #337.

### PR DESCRIPTION
**Pull request by vil02**
### Brief Summary of Changes

All changed classes are now marked as `final` and their _default_ constructor as `private` (i.e. it is _hidden_).

#### What does this PR address?
- [x] GitHub issue (Add reference - #340)
- [x] Refactoring
- [ ] New feature
- [ ] Bug fix
- [ ] Adds more tests

#### Are tests included?
- [ ] Yes
- [x] No

#### Reviewer, please note:

Fixes #340.

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I ran the full test suite before pushing the changes and all the tests pass.

### CODE REVIEW

**Comment by vil02** [comment]
@adimiz1, @michal-sordyl-cloudinary: is there anything else what I should do regarding this pull request?

**Comment by colbyfayock** [comment]
thanks @vil02 for the PR. This will be reviewed by the relevant SDK team member. 

While this will count towards hacktoberfest.com as the label is on the repository, just wanted to clarify that this will not count towards Cloudinary's Hacktoberfest swag based on the rules provided here: https://cld.media/hacktoberfest

we appreciate your contribution to improving the code health of the project!

**Comment by colbyfayock** [comment]
i think the confusion is that the person who was giving you the go ahead was just simply saying you could put together a PR when you asked:

> So... could I create a pull request fixing this?

but because i could see how that could be confusing we'll just let it count towards the swag pack if it's approved and merged

**Comment by vil02** [comment]
@colbyfayock: thanks! That is nice of you. Let's hope this will be merged in time.

**Review by adimiz1 — APPROVED** [review]

**Comment by colbyfayock** [comment]
@vil02 thanks for your contribution! this PR is eligible for free Cloudinary Hackatoberfest swag. Please send me an email at [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your name, GitHub username, and a link to the PR where I'll send further instructions.

Happy Hacktoberfest!

**Comment by vil02** [comment]
> @vil02 thanks for your contribution! this PR is eligible for free Cloudinary Hackatoberfest swag. Please send me an email at [hacktoberfest@cloudinary.com](mailto:hacktoberfest@cloudinary.com) with your name, GitHub username, and a link to the PR where I'll send further instructions.
> 
> Happy Hacktoberfest!

@colbyfayock: done.

**Pull request merged**
